export const MASTER_PRICE_META = Object.freeze({
  currency: "EGP",
  priceAsOf: "2026-09-24",
  source: "Carrefour Egypt category/product pages + Egyptian market reference",
  note: "200 منتج عالي الدوران للسوق المصري. الأسعار استرشادية بتاريخ 2026-09-24 وقد تختلف حسب المنطقة والعروض"
});

export const SUPERMARKET_MASTER_CATALOG = Object.freeze([
  { masterId:"nestle-water-600x20", brand:"Nestlé Pure Life", name:"نستله بيور لايف مياه شرب - 600 مل × 20", category:"مياه ومشروبات", size:"600 مل × 20", referencePrice:110.99, image:"" },
  { masterId:"nestle-water-15x12", brand:"Nestlé Pure Life", name:"نستله بيور لايف مياه شرب - 1.5 لتر × 12", category:"مياه ومشروبات", size:"1.5 لتر × 12", referencePrice:110.99, image:"" },
  { masterId:"aqua-delta-15x12", brand:"Aqua Delta", name:"أكوا دلتا مياه طبيعية - 1.5 لتر × 12", category:"مياه ومشروبات", size:"1.5 لتر × 12", referencePrice:118.99, image:"" },
  { masterId:"pepsi-300ml", brand:"Pepsi", name:"بيبسي - 300 مل", category:"مياه ومشروبات", size:"300 مل", referencePrice:17.99, image:"" },
  { masterId:"pepsi-1l", brand:"Pepsi", name:"بيبسي - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:27.99, image:"" },
  { masterId:"pepsi-2l", brand:"Pepsi", name:"بيبسي - 2 لتر", category:"مياه ومشروبات", size:"2 لتر", referencePrice:42.99, image:"" },
  { masterId:"cocacola-300", brand:"Coca-Cola", name:"كوكاكولا - 300 مل", category:"مياه ومشروبات", size:"300 مل", referencePrice:17.99, image:"" },
  { masterId:"cocacola-950ml", brand:"Coca-Cola", name:"كوكاكولا - 950 مل", category:"مياه ومشروبات", size:"950 مل", referencePrice:24.99, image:"" },
  { masterId:"cocacola-2l", brand:"Coca-Cola", name:"كوكاكولا - 2 لتر", category:"مياه ومشروبات", size:"2 لتر", referencePrice:42.99, image:"" },
  { masterId:"sprite-1l", brand:"Sprite", name:"سبرايت - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:27.99, image:"" },
  { masterId:"fanta-orange-1l", brand:"Fanta", name:"فانتا برتقال - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:27.99, image:"" },
  { masterId:"schweppes-gold-300", brand:"Schweppes", name:"شويبس جولد - 300 مل", category:"مياه ومشروبات", size:"300 مل", referencePrice:18.99, image:"" },
  { masterId:"vcola-300", brand:"V Cola", name:"في كولا سوبر صودا - 300 مل", category:"مياه ومشروبات", size:"300 مل", referencePrice:13.99, image:"" },
  { masterId:"redbull-250", brand:"Red Bull", name:"ريد بول مشروب طاقة - 250 مل", category:"مياه ومشروبات", size:"250 مل", referencePrice:54.99, image:"" },
  { masterId:"sting-250", brand:"Sting", name:"ستينج مشروب طاقة - 250 مل", category:"مياه ومشروبات", size:"250 مل", referencePrice:16.99, image:"" },
  { masterId:"beyti-apple-1l", brand:"Beyti Tropicana", name:"بيتي تروبيكانا عصير تفاح - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:37.99, image:"" },
  { masterId:"beyti-orange-1l", brand:"Beyti Tropicana", name:"بيتي تروبيكانا عصير برتقال - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:37.99, image:"" },
  { masterId:"juhayna-apple-1l", brand:"Juhayna", name:"جهينه كلاسيك عصير تفاح - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:37.99, image:"" },
  { masterId:"juhayna-orange-1l", brand:"Juhayna", name:"جهينه كلاسيك عصير برتقال - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:37.99, image:"" },
  { masterId:"juhayna-mango-1l", brand:"Juhayna", name:"جهينه كلاسيك عصير مانجو - 1 لتر", category:"مياه ومشروبات", size:"1 لتر", referencePrice:39.99, image:"" },
  { masterId:"juhayna-choco-200", brand:"Juhayna", name:"جهينه ميكس لبن بالشوكولاتة - 200 مل", category:"مياه ومشروبات", size:"200 مل", referencePrice:10.5, image:"" },
  { masterId:"nescafe-3in1-24", brand:"Nescafé", name:"نسكافيه 3 في 1 أوريجينال - 24 كيس", category:"قهوة وشاي", size:"18 جم × 24", referencePrice:142.99, image:"" },
  { masterId:"nescafe-classic-190g", brand:"Nescafé", name:"نسكافيه كلاسيك قهوة سريعة الذوبان - 190 جم", category:"قهوة وشاي", size:"190 جم", referencePrice:280.99, image:"" },
  { masterId:"nescafe-gold-190", brand:"Nescafé", name:"نسكافيه جولد - 190 جم", category:"قهوة وشاي", size:"190 جم", referencePrice:438.99, image:"" },
  { masterId:"lipton-tea-100g", brand:"Lipton", name:"ليبتون شاي - 100 جم", category:"قهوة وشاي", size:"100 جم", referencePrice:31.5, image:"" },
  { masterId:"almarai-milk-1l", brand:"Almarai", name:"المراعي حليب كامل الدسم - 1 لتر", category:"ألبان وبيض", size:"1 لتر", referencePrice:44.5, image:"" },
  { masterId:"obourland-milk-1l", brand:"Obour Land", name:"عبور لاند حليب كامل الدسم - 1 لتر", category:"ألبان وبيض", size:"1 لتر", referencePrice:43.99, image:"" },
  { masterId:"lamar-milk-1l", brand:"Lamar", name:"لمار حليب كامل الدسم - 1 لتر", category:"ألبان وبيض", size:"1 لتر", referencePrice:44.5, image:"" },
  { masterId:"juhayna-milk-1l", brand:"Juhayna", name:"جهينه حليب كامل الدسم - 1 لتر", category:"ألبان وبيض", size:"1 لتر", referencePrice:53.99, image:"" },
  { masterId:"beyti-milk-900ml", brand:"Beyti", name:"بيتي لبن كامل الدسم - 900 مل", category:"ألبان وبيض", size:"900 مل", referencePrice:44.5, image:"" },
  { masterId:"labanita-milk-1l", brand:"Labanita", name:"لبنيتا حليب كامل الدسم - 1 لتر", category:"ألبان وبيض", size:"1 لتر", referencePrice:48.99, image:"" },
  { masterId:"almarai-milk-200", brand:"Almarai", name:"المراعي حليب كامل الدسم - 200 مل", category:"ألبان وبيض", size:"200 مل", referencePrice:10.5, image:"" },
  { masterId:"almarai-yogurt-105x6", brand:"Almarai", name:"المراعي زبادي طبيعي - 105 جم × 6", category:"ألبان وبيض", size:"105 جم × 6", referencePrice:52.99, image:"" },
  { masterId:"almarai-yogurt-105x12", brand:"Almarai", name:"المراعي زبادي طبيعي - 105 جم × 12", category:"ألبان وبيض", size:"105 جم × 12", referencePrice:74.99, image:"" },
  { masterId:"juhayna-yogurt-105x12", brand:"Juhayna", name:"جهينه زبادي طبيعي - 105 جم × 12", category:"ألبان وبيض", size:"105 جم × 12", referencePrice:74.99, image:"" },
  { masterId:"danone-yogurt-85x12", brand:"Danone", name:"دانون زبادي سادة - 85 جم × 12", category:"ألبان وبيض", size:"85 جم × 12", referencePrice:82.99, image:"" },
  { masterId:"almarai-greek-170", brand:"Almarai", name:"المراعي زبادي يوناني 5% - 170 جم", category:"ألبان وبيض", size:"170 جم", referencePrice:31.99, image:"" },
  { masterId:"domty-talage-low-250", brand:"Domty", name:"دومتي جبنة ثلاجة ملح خفيف - 250 جم", category:"جبن", size:"250 جم", referencePrice:34.99, image:"" },
  { masterId:"domty-doublecream-250", brand:"Domty", name:"دومتي جبنة دوبل كريم - 250 جم", category:"جبن", size:"250 جم", referencePrice:41.25, image:"" },
  { masterId:"domty-feta-250g", brand:"Domty", name:"دومتي جبنة فيتا طبيعي - 250 جم", category:"جبن", size:"250 جم", referencePrice:41.25, image:"" },
  { masterId:"domty-bramily-250", brand:"Domty", name:"دومتي جبنة براميلي - 250 جم", category:"جبن", size:"250 جم", referencePrice:36, image:"" },
  { masterId:"obourland-feta-500", brand:"Obour Land", name:"عبور لاند جبنة فيتا طبيعي - 500 جم", category:"جبن", size:"500 جم", referencePrice:77.99, image:"" },
  { masterId:"abu-alwalad-triangle-32", brand:"Abu Al Walad", name:"أبو الولد جبنة مثلثات - 32 قطعة", category:"جبن", size:"32 قطعة", referencePrice:119.99, image:"" },
  { masterId:"kiri-triangle-16", brand:"Kiri", name:"كيري جبنة مثلثات - 16 قطعة", category:"جبن", size:"16 قطعة", referencePrice:124.99, image:"" },
  { masterId:"president-triangle-16", brand:"Président", name:"بريزيدن جبنة مثلثات - 16 قطعة", category:"جبن", size:"16 قطعة", referencePrice:99.99, image:"" },
  { masterId:"dinafarms-low-salt-450", brand:"Dina Farms", name:"دينا فارمز جبنة ملح خفيف - 450 جم", category:"جبن", size:"450 جم", referencePrice:111.99, image:"" },
  { masterId:"katilo-low-salt-250", brand:"Katilo", name:"كاتيلو جبنة ملح خفيف - 250 جم", category:"جبن", size:"250 جم", referencePrice:47.5, image:"" },
  { masterId:"perla-feta-250", brand:"Perla", name:"بيرلا جبنة فيتا - 250 جم", category:"جبن", size:"250 جم", referencePrice:37.5, image:"" },
  { masterId:"perla-cottage-250", brand:"Perla", name:"بيرلا جبنة قريش - 250 جم", category:"جبن", size:"250 جم", referencePrice:30, image:"" },
  { masterId:"lurpak-butter-200", brand:"Lurpak", name:"لورباك زبدة غير مملحة - 200 جم", category:"ألبان وبيض", size:"200 جم", referencePrice:174.99, image:"" },
  { masterId:"fern-butter-1kg", brand:"Fern", name:"فيرن زبدة مخلوطة - 1 كجم", category:"ألبان وبيض", size:"1 كجم", referencePrice:156.99, image:"" },
  { masterId:"royal-eggs-30", brand:"Royal", name:"رويال بيض أبيض - 30 بيضة", category:"ألبان وبيض", size:"30 بيضة", referencePrice:99.99, image:"" },
  { masterId:"white-eggs-12", brand:"Local", name:"بيض أبيض - 12 بيضة", category:"ألبان وبيض", size:"12 بيضة", referencePrice:48.99, image:"" },
  { masterId:"cream-cooking-500", brand:"Cooking Cream", name:"كريمة طبخ - 500 مل", category:"ألبان وبيض", size:"500 مل", referencePrice:84.99, image:"" },
  { masterId:"mozzarella-200", brand:"Mozzarella", name:"جبنة موزاريلا - 200 جم", category:"جبن", size:"200 جم", referencePrice:79.99, image:"" },
  { masterId:"aldoha-rice-1kg", brand:"Al Doha", name:"الضحى أرز مصري - 1 كجم", category:"أرز ومكرونة وبقوليات", size:"1 كجم", referencePrice:39.99, image:"" },
  { masterId:"almazag-rice-1kg", brand:"Al Mazag", name:"المزاج أرز أبيض مصري - 1 كجم", category:"أرز ومكرونة وبقوليات", size:"1 كجم", referencePrice:25.5, image:"" },
  { masterId:"ahlalqema-rice-1kg", brand:"Ahl Alqema", name:"أهل القمة أرز أبيض - 1 كجم", category:"أرز ومكرونة وبقوليات", size:"1 كجم", referencePrice:24.99, image:"" },
  { masterId:"matbakh-rice-1kg", brand:"El Matbakh", name:"المطبخ أرز أبيض - 1 كجم", category:"أرز ومكرونة وبقوليات", size:"1 كجم", referencePrice:38.99, image:"" },
  { masterId:"rehana-rice-1kg", brand:"Rehana", name:"ريحانة أرز أبيض مصري - 1 كجم", category:"أرز ومكرونة وبقوليات", size:"1 كجم", referencePrice:36.5, image:"" },
  { masterId:"aldoha-sugar-1kg", brand:"Al Doha", name:"الضحى سكر أبيض - 1 كجم", category:"سكر ودقيق ومخبوزات", size:"1 كجم", referencePrice:34.99, image:"" },
  { masterId:"almazag-sugar-1kg", brand:"Al Mazag", name:"المزاج سكر أبيض - 1 كجم", category:"سكر ودقيق ومخبوزات", size:"1 كجم", referencePrice:29.99, image:"" },
  { masterId:"almazag-flour-1kg", brand:"Al Mazag", name:"المزاج دقيق أبيض متعدد الاستخدام - 1 كجم", category:"سكر ودقيق ومخبوزات", size:"1 كجم", referencePrice:21.99, image:"" },
  { masterId:"daria-flour-1kg", brand:"Daria", name:"داريا دقيق أبيض متعدد الاستخدام - 1 كجم", category:"سكر ودقيق ومخبوزات", size:"1 كجم", referencePrice:39.99, image:"" },
  { masterId:"regina-spaghetti-400g", brand:"Regina", name:"ريجينا مكرونة اسباجتي - 400 جم", category:"أرز ومكرونة وبقوليات", size:"400 جم", referencePrice:30.99, image:"" },
  { masterId:"aldoha-pasta-400g", brand:"Al Doha", name:"الضحى مكرونة هلالية - 400 جم", category:"أرز ومكرونة وبقوليات", size:"400 جم", referencePrice:25.99, image:"" },
  { masterId:"italiano-spaghetti-400", brand:"Italiano", name:"إيطاليانو مكرونة اسباجتي - 400 جم", category:"أرز ومكرونة وبقوليات", size:"400 جم", referencePrice:27.99, image:"" },
  { masterId:"queen-pasta-400", brand:"Queen", name:"كوين مكرونة - 400 جم", category:"أرز ومكرونة وبقوليات", size:"400 جم", referencePrice:18.99, image:"" },
  { masterId:"crystal-oil-1l", brand:"Crystal", name:"كريستال زيت عباد الشمس - 1 لتر", category:"زيوت وسمن", size:"1 لتر", referencePrice:107.5, image:"" },
  { masterId:"crystal-oil-22l", brand:"Crystal", name:"كريستال زيت عباد الشمس - 2.2 لتر", category:"زيوت وسمن", size:"2.2 لتر", referencePrice:237.5, image:"" },
  { masterId:"afia-oil-22l", brand:"Afia", name:"عافية زيت عباد الشمس - 2.2 لتر", category:"زيوت وسمن", size:"2.2 لتر", referencePrice:221.99, image:"" },
  { masterId:"helwa-oil-225l", brand:"Helwa", name:"حلوة زيت مخلوط - 2.25 لتر", category:"زيوت وسمن", size:"2.25 لتر", referencePrice:181.5, image:"" },
  { masterId:"crystal-ghee-15kg", brand:"Crystal", name:"كريستال سمن نباتي - 1.5 كجم", category:"زيوت وسمن", size:"1.5 كجم", referencePrice:180.99, image:"" },
  { masterId:"aldoha-lentils-500", brand:"Al Doha", name:"الضحى عدس أصفر - 500 جم", category:"أرز ومكرونة وبقوليات", size:"500 جم", referencePrice:49.99, image:"" },
  { masterId:"aldoha-beans-500", brand:"Al Doha", name:"الضحى فول تدميس - 500 جم", category:"أرز ومكرونة وبقوليات", size:"500 جم", referencePrice:44.99, image:"" },
  { masterId:"aldoha-chickpeas-500", brand:"Al Doha", name:"الضحى حمص - 500 جم", category:"أرز ومكرونة وبقوليات", size:"500 جم", referencePrice:59.99, image:"" },
  { masterId:"aldoha-blackeyed-500", brand:"Al Doha", name:"الضحى لوبيا - 500 جم", category:"أرز ومكرونة وبقوليات", size:"500 جم", referencePrice:54.99, image:"" },
  { masterId:"knorr-stock-chicken-8", brand:"Knorr", name:"كنور مكعبات مرقة دجاج - 8 مكعبات", category:"توابل ومكونات طبخ", size:"8 مكعبات", referencePrice:27.99, image:"" },
  { masterId:"knorr-stock-beef-8", brand:"Knorr", name:"كنور مكعبات مرقة لحم - 8 مكعبات", category:"توابل ومكونات طبخ", size:"8 مكعبات", referencePrice:27.99, image:"" },
  { masterId:"dreem-bakingpowder-23", brand:"Dreem", name:"دريم بيكنج باودر - 23 جم", category:"سكر ودقيق ومخبوزات", size:"23 جم", referencePrice:5.99, image:"" },
  { masterId:"dreem-vanilla-2", brand:"Dreem", name:"دريم فانيليا - 2 جم", category:"سكر ودقيق ومخبوزات", size:"2 جم", referencePrice:1.5, image:"" },
  { masterId:"dreem-yeast-11", brand:"Dreem", name:"دريم خميرة فورية - 11 جم", category:"سكر ودقيق ومخبوزات", size:"11 جم", referencePrice:4.5, image:"" },
  { masterId:"heinz-ketchup-340", brand:"Heinz", name:"هاينز كاتشب - 340 جم", category:"صلصات ومعلبات", size:"340 جم", referencePrice:64.99, image:"" },
  { masterId:"heinz-mayo-285", brand:"Heinz", name:"هاينز مايونيز - 285 مل", category:"صلصات ومعلبات", size:"285 مل", referencePrice:79.99, image:"" },
  { masterId:"americana-tomato-paste-300", brand:"Americana", name:"أمريكانا صلصة طماطم - 300 جم", category:"صلصات ومعلبات", size:"300 جم", referencePrice:28.99, image:"" },
  { masterId:"sunshine-tuna-185", brand:"Sunshine", name:"صن شاين تونة قطع - 185 جم", category:"صلصات ومعلبات", size:"185 جم", referencePrice:74.99, image:"" },
  { masterId:"dolphin-tuna-185", brand:"Dolphin", name:"دولفين تونة قطع - 185 جم", category:"صلصات ومعلبات", size:"185 جم", referencePrice:69.99, image:"" },
  { masterId:"california-garden-fava-400", brand:"California Garden", name:"كاليفورنيا جاردن فول مدمس - 400 جم", category:"صلصات ومعلبات", size:"400 جم", referencePrice:39.99, image:"" },
  { masterId:"americana-fava-400", brand:"Americana", name:"أمريكانا فول مدمس - 400 جم", category:"صلصات ومعلبات", size:"400 جم", referencePrice:29.99, image:"" },
  { masterId:"halwani-tahina-400", brand:"Halwani", name:"حلواني طحينة - 400 جم", category:"صلصات ومعلبات", size:"400 جم", referencePrice:89.99, image:"" },
  { masterId:"elrashidi-tahina-400", brand:"El Rashidi El Mizan", name:"الرشيدي الميزان طحينة - 400 جم", category:"صلصات ومعلبات", size:"400 جم", referencePrice:84.99, image:"" },
  { masterId:"elrashidi-halwa-900", brand:"El Rashidi El Mizan", name:"الرشيدي الميزان حلاوة سادة - 900 جم", category:"فطار وسبريد", size:"900 جم", referencePrice:169.99, image:"" },
  { masterId:"elbawadi-halwa-970", brand:"El Bawadi", name:"البوادي حلاوة سادة - 970 جم", category:"فطار وسبريد", size:"970 جم", referencePrice:158.99, image:"" },
  { masterId:"water-aquafina-15l", brand:"Aquafina", name:"أكوافينا مياه طبيعية - 1.5 لتر", category:"مياه ومشروبات", size:"1.5 لتر", referencePrice:10.5, image:"" },
  { masterId:"juhayna-greek-yogurt-180g", brand:"Juhayna", name:"جهينه زبادي يوناني 2% دسم - 180 جم", category:"ألبان وبيض", size:"180 جم", referencePrice:40.99, image:"" },
  { masterId:"chipsy-cheese-140g", brand:"Chipsy", name:"شيبسي رقائق بطاطس بالجبنة والبصل - 140 جم", category:"سناكس وبسكويت", size:"140 جم", referencePrice:18.5, image:"" },
  { masterId:"chipsy-salt-140", brand:"Chipsy", name:"شيبسي ملح - 140 جم", category:"سناكس وبسكويت", size:"140 جم", referencePrice:18.5, image:"" },
  { masterId:"chipsy-chili-140", brand:"Chipsy", name:"شيبسي شطة وليمون - 140 جم", category:"سناكس وبسكويت", size:"140 جم", referencePrice:18.5, image:"" },
  { masterId:"tiger-lime-58", brand:"Tiger", name:"تايجر ليمون وكزبرة - 58 جم", category:"سناكس وبسكويت", size:"58 جم", referencePrice:14.99, image:"" },
  { masterId:"tiger-sweetchili-58", brand:"Tiger", name:"تايجر سويت تشيلي - 58 جم", category:"سناكس وبسكويت", size:"58 جم", referencePrice:14.99, image:"" },
  { masterId:"bakerolz-ketchup-45", brand:"Bake Rolz", name:"بيك رولز كاتشب - 45 جم", category:"سناكس وبسكويت", size:"45 جم", referencePrice:9.99, image:"" },
  { masterId:"bakerolz-cheese-45", brand:"Bake Rolz", name:"بيك رولز جبنة - 45 جم", category:"سناكس وبسكويت", size:"45 جم", referencePrice:9.99, image:"" },
  { masterId:"balance-cheese-70", brand:"Balance", name:"بالانس بروتين بافس جبنة - 70 جم", category:"سناكس وبسكويت", size:"70 جم", referencePrice:14.99, image:"" },
  { masterId:"balance-puffs-70g", brand:"Balance", name:"بالانس بروتين بافس بطعم الذرة الحلوة - 70 جم", category:"سناكس وبسكويت", size:"70 جم", referencePrice:14.99, image:"" },
  { masterId:"pringles-ketchup-165", brand:"Pringles", name:"برينجلز كاتشب - 165 جم", category:"سناكس وبسكويت", size:"165 جم", referencePrice:131.99, image:"" },
  { masterId:"pringles-cheese-165", brand:"Pringles", name:"برينجلز جبنة - 165 جم", category:"سناكس وبسكويت", size:"165 جم", referencePrice:131.99, image:"" },
  { masterId:"pringles-paprika-165", brand:"Pringles", name:"برينجلز بابريكا - 165 جم", category:"سناكس وبسكويت", size:"165 جم", referencePrice:153.99, image:"" },
  { masterId:"abuauf-pretzels-salt-250", brand:"Abu Auf", name:"أبو عوف بريتزل ملح - 250 جم", category:"سناكس وبسكويت", size:"250 جم", referencePrice:38.99, image:"" },
  { masterId:"abuauf-pretzels-ketchup-250", brand:"Abu Auf", name:"أبو عوف بريتزل كاتشب - 250 جم", category:"سناكس وبسكويت", size:"250 جم", referencePrice:38.99, image:"" },
  { masterId:"oreo-vanilla-80", brand:"Oreo", name:"أوريو بسكويت فانيليا - 80 جم", category:"سناكس وبسكويت", size:"80 جم", referencePrice:13.99, image:"" },
  { masterId:"oreo-choco-hazelnut-48", brand:"Oreo", name:"أوريو شوكولاتة وبندق - 48 جم", category:"سناكس وبسكويت", size:"48 جم", referencePrice:7.99, image:"" },
  { masterId:"mcvities-digestive-400", brand:"McVitie's", name:"مكفيتيز دايجستف أوريجينال - 400 جم", category:"سناكس وبسكويت", size:"400 جم", referencePrice:57.5, image:"" },
  { masterId:"mcvities-light-250", brand:"McVitie's", name:"مكفيتيز دايجستف لايت - 250 جم", category:"سناكس وبسكويت", size:"250 جم", referencePrice:36.99, image:"" },
  { masterId:"ulker-tea-12", brand:"Ülker", name:"أولكر بسكويت شاي - 12 قطعة", category:"سناكس وبسكويت", size:"12 قطعة", referencePrice:59.5, image:"" },
  { masterId:"biscomisr-luxe-12", brand:"Bisco Misr", name:"بسكو مصر لوكس أوريجينال - 12 قطعة", category:"سناكس وبسكويت", size:"12 قطعة", referencePrice:59.5, image:"" },
  { masterId:"mandolin-choco-40", brand:"Mandolin", name:"ماندولين شوكولاتة - 40 جم", category:"سناكس وبسكويت", size:"40 جم", referencePrice:9.99, image:"" },
  { masterId:"shamadan-katakito-5", brand:"El Shamadan", name:"الشمعدان كتاكيتو ويفر شوكولاتة - 5 قطع", category:"سناكس وبسكويت", size:"5 قطع", referencePrice:89.99, image:"" },
  { masterId:"corona-bimbo-37", brand:"Corona", name:"كورونا بيمبو بسكويت شوكولاتة - 37 جم", category:"سناكس وبسكويت", size:"37 جم", referencePrice:5.99, image:"" },
  { masterId:"cadbury-delight-25", brand:"Cadbury", name:"كادبوري ديلايت بسكويت شوكولاتة - 25.5 جم", category:"سناكس وبسكويت", size:"25.5 جم", referencePrice:12.99, image:"" },
  { masterId:"cadbury-dairymilk-85", brand:"Cadbury", name:"كادبوري ديري ميلك - 85 جم", category:"شوكولاتة وحلويات", size:"85 جم", referencePrice:78.99, image:"" },
  { masterId:"cadbury-hazelnut-85", brand:"Cadbury", name:"كادبوري ديري ميلك بندق - 85 جم", category:"شوكولاتة وحلويات", size:"85 جم", referencePrice:78.99, image:"" },
  { masterId:"galaxy-milk-80", brand:"Galaxy", name:"جالاكسي شوكولاتة حليب - 80 جم", category:"شوكولاتة وحلويات", size:"80 جم", referencePrice:70.99, image:"" },
  { masterId:"galaxy-hazelnut-80", brand:"Galaxy", name:"جالاكسي شوكولاتة بندق - 80 جم", category:"شوكولاتة وحلويات", size:"80 جم", referencePrice:70.99, image:"" },
  { masterId:"galaxy-flutes-45", brand:"Galaxy", name:"جالاكسي فلوتس ويفر - 45 جم", category:"شوكولاتة وحلويات", size:"45 جم", referencePrice:17.99, image:"" },
  { masterId:"twix-58", brand:"Twix", name:"تويكس شوكولاتة - 58 جم", category:"شوكولاتة وحلويات", size:"58 جم", referencePrice:28.99, image:"" },
  { masterId:"snickers-50", brand:"Snickers", name:"سنيكرز شوكولاتة - 50 جم", category:"شوكولاتة وحلويات", size:"50 جم", referencePrice:29.99, image:"" },
  { masterId:"kitkat-4finger", brand:"KitKat", name:"كيت كات 4 أصابع - 41.5 جم", category:"شوكولاتة وحلويات", size:"41.5 جم", referencePrice:31.99, image:"" },
  { masterId:"kinder-bueno-43", brand:"Kinder Bueno", name:"كيندر بوينو - 43 جم", category:"شوكولاتة وحلويات", size:"43 جم", referencePrice:43.5, image:"" },
  { masterId:"mms-45", brand:"M&M's", name:"إم آند إمز شوكولاتة حليب - 45 جم", category:"شوكولاتة وحلويات", size:"45 جم", referencePrice:43.99, image:"" },
  { masterId:"nutella-biscuits-14", brand:"Nutella", name:"نوتيلا بسكويت - 14 قطعة", category:"سناكس وبسكويت", size:"14 قطعة", referencePrice:174.99, image:"" },
  { masterId:"ferrero-rocher-16", brand:"Ferrero Rocher", name:"فيريرو روشيه - 16 قطعة", category:"شوكولاتة وحلويات", size:"200 جم", referencePrice:412.99, image:"" },
  { masterId:"milka-milk-98", brand:"Milka", name:"ميلكا شوكولاتة حليب - 98 جم", category:"شوكولاتة وحلويات", size:"98 جم", referencePrice:109.5, image:"" },
  { masterId:"clorets-lemon-168", brand:"Clorets", name:"كلوريتس علكة ليمون ونعناع - 16.8 جم", category:"شوكولاتة وحلويات", size:"16.8 جم", referencePrice:14.99, image:"" },
  { masterId:"katakito-wafer", brand:"Katakito", name:"كتاكيتو إكسترا ويفر بالحليب - قطعة", category:"سناكس وبسكويت", size:"قطعة", referencePrice:21.99, image:"" },
  { masterId:"toffix-650", brand:"Toffix", name:"توفيكس توفي فواكه - 650 جم", category:"شوكولاتة وحلويات", size:"650 جم", referencePrice:114.99, image:"" },
  { masterId:"nutella-350", brand:"Nutella", name:"نوتيلا سبريد بندق وكاكاو - 350 جم", category:"فطار وسبريد", size:"350 جم", referencePrice:240.99, image:"" },
  { masterId:"nutella-600", brand:"Nutella", name:"نوتيلا سبريد بندق وكاكاو - 600 جم", category:"فطار وسبريد", size:"600 جم", referencePrice:381.5, image:"" },
  { masterId:"dreem-choco-900", brand:"Dreem", name:"دريم وندر شوكولاتة سبريد - 900 جم", category:"فطار وسبريد", size:"900 جم", referencePrice:338.5, image:"" },
  { masterId:"abuauf-peanutbutter-300", brand:"Abu Auf", name:"أبو عوف زبدة فول سوداني - 300 جم", category:"فطار وسبريد", size:"300 جم", referencePrice:129.99, image:"" },
  { masterId:"hero-strawberry-350", brand:"Hero", name:"هيرو مربى فراولة - 350 جم", category:"فطار وسبريد", size:"350 جم", referencePrice:79.99, image:"" },
  { masterId:"hero-apricot-350", brand:"Hero", name:"هيرو مربى مشمش - 350 جم", category:"فطار وسبريد", size:"350 جم", referencePrice:79.99, image:"" },
  { masterId:"vitrac-strawberry-430", brand:"Vitrac", name:"فيتراك مربى فراولة - 430 جم", category:"فطار وسبريد", size:"430 جم", referencePrice:69.99, image:"" },
  { masterId:"vitrac-apricot-430", brand:"Vitrac", name:"فيتراك مربى مشمش - 430 جم", category:"فطار وسبريد", size:"430 جم", referencePrice:69.99, image:"" },
  { masterId:"imtenan-honey-350", brand:"Imtenan", name:"امتنان عسل نحل - 350 جم", category:"فطار وسبريد", size:"350 جم", referencePrice:169.99, image:"" },
  { masterId:"elbawadi-honey-350", brand:"El Bawadi", name:"البوادي عسل نحل - 350 جم", category:"فطار وسبريد", size:"350 جم", referencePrice:129.99, image:"" },
  { masterId:"kelloggs-cornflakes-375", brand:"Kellogg's", name:"كيلوجز كورن فليكس - 375 جم", category:"فطار وسبريد", size:"375 جم", referencePrice:159.99, image:"" },
  { masterId:"fitness-cereal-375", brand:"Nestlé Fitness", name:"نستله فيتنس حبوب إفطار - 375 جم", category:"فطار وسبريد", size:"375 جم", referencePrice:174.99, image:"" },
  { masterId:"nesquik-cereal-375", brand:"Nesquik", name:"نسكويك حبوب إفطار شوكولاتة - 375 جم", category:"فطار وسبريد", size:"375 جم", referencePrice:169.99, image:"" },
  { masterId:"quaker-oats-500", brand:"Quaker", name:"كويكر شوفان - 500 جم", category:"فطار وسبريد", size:"500 جم", referencePrice:89.99, image:"" },
  { masterId:"almarai-cream-cheese-200", brand:"Almarai", name:"المراعي جبنة كريمي قابلة للدهن - 200 جم", category:"فطار وسبريد", size:"200 جم", referencePrice:84.99, image:"" },
  { masterId:"ariel-downy-gel-36", brand:"Ariel", name:"أريال باور جل بلمسة داوني - 3.6 لتر", category:"منظفات ومنزل", size:"3.6 لتر", referencePrice:289.99, image:"" },
  { masterId:"ariel-lavender-gel-36", brand:"Ariel", name:"أريال باور جل لافندر - 3.6 لتر", category:"منظفات ومنزل", size:"3.6 لتر", referencePrice:289.99, image:"" },
  { masterId:"persil-deep-8kg", brand:"Persil", name:"برسيل ديب كلين أوتوماتيك - 8 كجم", category:"منظفات ومنزل", size:"8 كجم", referencePrice:464.99, image:"" },
  { masterId:"persil-gel-265", brand:"Persil", name:"برسيل باور جل - 2.65 لتر", category:"منظفات ومنزل", size:"2.65 لتر", referencePrice:224.99, image:"" },
  { masterId:"tide-downy-gel-3", brand:"Tide", name:"تايد باور جل بلمسة داوني - 3 لتر", category:"منظفات ومنزل", size:"3 لتر", referencePrice:229.99, image:"" },
  { masterId:"tide-lavender-3", brand:"Tide", name:"تايد أوتوماتيك جل لافندر - 3 لتر", category:"منظفات ومنزل", size:"3 لتر", referencePrice:229.99, image:"" },
  { masterId:"oxi-auto-25", brand:"Oxi", name:"أوكسي أوتوماتيك لافندر - 2.5 كجم", category:"منظفات ومنزل", size:"2.5 كجم", referencePrice:188.99, image:"" },
  { masterId:"bahi-lavender-2", brand:"Bahi", name:"باهي مسحوق غسيل لافندر - 2 كجم", category:"منظفات ومنزل", size:"2 كجم", referencePrice:143.99, image:"" },
  { masterId:"clorox-color-189", brand:"Clorox", name:"كلوركس ألوان - 1.89 لتر", category:"منظفات ومنزل", size:"1.89 لتر", referencePrice:124.99, image:"" },
  { masterId:"cloro-regular-1", brand:"Cloro", name:"كلورو مبيض عادي - 1 لتر", category:"منظفات ومنزل", size:"1 لتر", referencePrice:24.99, image:"" },
  { masterId:"pril-lemon-25", brand:"Pril", name:"بريل سائل غسيل أطباق ليمون أخضر - 2.5 لتر", category:"منظفات ومنزل", size:"2.5 لتر", referencePrice:132.5, image:"" },
  { masterId:"pril-lemon-4", brand:"Pril", name:"بريل سائل غسيل أطباق ليمون - 4 لتر", category:"منظفات ومنزل", size:"4 لتر", referencePrice:209.99, image:"" },
  { masterId:"shiny-dish-4l", brand:"Shiny", name:"شايني سائل غسيل أطباق بالليمون - 4 لتر", category:"منظفات ومنزل", size:"4 لتر", referencePrice:99.99, image:"" },
  { masterId:"fairy-lemon-620g", brand:"Fairy", name:"فيري سائل غسيل أطباق برائحة الليمون - 620 جم", category:"منظفات ومنزل", size:"620 جم", referencePrice:109.99, image:"" },
  { masterId:"persil-lavender-1kg", brand:"Persil", name:"برسيل مسحوق غسيل برائحة اللافندر - 1 كجم", category:"منظفات ومنزل", size:"1 كجم", referencePrice:78.5, image:"" },
  { masterId:"zeina-tissues-500x6", brand:"Zeina", name:"زينة مناديل ناعمة 500 منديل - 6 عبوات", category:"ورقيات", size:"500 منديل × 6", referencePrice:199.99, image:"" },
  { masterId:"zeina-toilet-12", brand:"Zeina", name:"زينة رول تواليت مضغوط 10+2", category:"ورقيات", size:"12 رول", referencePrice:153.99, image:"" },
  { masterId:"papia-toilet-12", brand:"Papia", name:"بابيا رول تواليت 10+2", category:"ورقيات", size:"12 رول", referencePrice:129.99, image:"" },
  { masterId:"zeina-kitchen-12", brand:"Zeina", name:"زينة مناديل مطبخ - 12 رول", category:"ورقيات", size:"12 رول", referencePrice:127.99, image:"" },
  { masterId:"zeina-kitchen-6", brand:"Zeina", name:"زينة مناديل مطبخ - 6 رول", category:"ورقيات", size:"6 رول", referencePrice:81.99, image:"" },
  { masterId:"white-tissues-500x6", brand:"White", name:"وايت فليكسي مناديل 500 منديل - 6 عبوات", category:"ورقيات", size:"500 منديل × 6", referencePrice:199.99, image:"" },
  { masterId:"familia-tissues-500x6", brand:"Familia", name:"فاميليا مناديل 3 طبقات 500 منديل - 6 عبوات", category:"ورقيات", size:"500 منديل × 6", referencePrice:164.99, image:"" },
  { masterId:"sanita-garbage-large", brand:"Sanita", name:"سانيتا أكياس قمامة كبيرة", category:"منظفات ومنزل", size:"عبوة", referencePrice:79.99, image:"" },
  { masterId:"glad-cling-film", brand:"Glad", name:"جلاد نايلون تغليف طعام", category:"منظفات ومنزل", size:"رول", referencePrice:69.99, image:"" },
  { masterId:"fresh-foil-30m", brand:"Fresh", name:"فويل ألومنيوم - 30 متر", category:"منظفات ومنزل", size:"30 متر", referencePrice:79.99, image:"" },
  { masterId:"signal-anticavity-120ml", brand:"Signal", name:"سيجنال معجون أسنان مكافح للتسوس - 120 مل", category:"عناية شخصية", size:"120 مل", referencePrice:48.5, image:"" },
  { masterId:"closeup-100ml", brand:"Closeup", name:"كلوس أب معجون أسنان بالمينتول الأخضر - 100 مل", category:"عناية شخصية", size:"100 مل", referencePrice:48.5, image:"" },
  { masterId:"sensodyne-75", brand:"Sensodyne", name:"سنسوداين معجون أسنان - 75 مل", category:"عناية شخصية", size:"75 مل", referencePrice:139.99, image:"" },
  { masterId:"parodontax-50", brand:"Parodontax", name:"بارودونتكس معجون أسنان إكسترا فريش - 50 مل", category:"عناية شخصية", size:"50 مل", referencePrice:122.5, image:"" },
  { masterId:"listerine-500", brand:"Listerine", name:"ليسترين غسول فم توتال كير - 500 مل", category:"عناية شخصية", size:"500 مل", referencePrice:190.99, image:"" },
  { masterId:"lux-soap-115", brand:"Lux", name:"لوكس صابون كريمي - 115 جم", category:"عناية شخصية", size:"115 جم", referencePrice:24.99, image:"" },
  { masterId:"lux-soap-4x115g", brand:"Lux", name:"لوكس صابون - 115 جم × 4 قطع", category:"عناية شخصية", size:"4 قطع × 115 جم", referencePrice:102.5, image:"" },
  { masterId:"lifebuoy-soap-115x4", brand:"Lifebuoy", name:"لايفبوي صابون - 115 جم × 4", category:"عناية شخصية", size:"115 جم × 4", referencePrice:112.5, image:"" },
  { masterId:"dove-pink-90", brand:"Dove", name:"دوف صابون بينك بيوتي - 90 جم", category:"عناية شخصية", size:"90 جم", referencePrice:43.5, image:"" },
  { masterId:"dove-bodywash-500", brand:"Dove", name:"دوف شاور جل ديبلي نورشينج - 500 مل", category:"عناية شخصية", size:"500 مل", referencePrice:99.99, image:"" },
  { masterId:"lux-shower-500", brand:"Lux", name:"لوكس شاور جل ماجيكال أوركيد - 500 مل", category:"عناية شخصية", size:"500 مل", referencePrice:83.99, image:"" },
  { masterId:"pantene-repair-400", brand:"Pantene", name:"بانتين برو في إصلاح التلف - 400 مل", category:"عناية شخصية", size:"400 مل", referencePrice:196.99, image:"" },
  { masterId:"pantene-daily-400", brand:"Pantene", name:"بانتين برو في عناية يومية - 400 مل", category:"عناية شخصية", size:"400 مل", referencePrice:159.99, image:"" },
  { masterId:"sunsilk-restore-600", brand:"Sunsilk", name:"صانسيلك شامبو إصلاح فوري - 600 مل", category:"عناية شخصية", size:"600 مل", referencePrice:114.99, image:"" },
  { masterId:"sunsilk-hairfall-350", brand:"Sunsilk", name:"صانسيلك شامبو ضد تساقط الشعر - 350 مل", category:"عناية شخصية", size:"350 مل", referencePrice:114.99, image:"" },
  { masterId:"dove-repair-180", brand:"Dove", name:"دوف شامبو إصلاح مكثف - 180 مل", category:"عناية شخصية", size:"180 مل", referencePrice:88.99, image:"" },
  { masterId:"tresemme-keratin-400", brand:"TRESemmé", name:"تريسمي شامبو كيراتين سموث - 400 مل", category:"عناية شخصية", size:"400 مل", referencePrice:187.5, image:"" },
  { masterId:"nivea-men-deep-150", brand:"Nivea", name:"نيفيا مين ديب سبراي مضاد تعرق - 150 مل", category:"عناية شخصية", size:"150 مل", referencePrice:119.99, image:"" },
  { masterId:"axe-spray-150", brand:"Axe", name:"أكس مزيل عرق سبراي - 150 مل", category:"عناية شخصية", size:"150 مل", referencePrice:199.5, image:"" },
  { masterId:"gillette-blue3", brand:"Gillette", name:"جيليت بلو 3 شفرات حلاقة", category:"عناية شخصية", size:"عبوة", referencePrice:139.99, image:"" },
  { masterId:"farmfrites-fries-1kg", brand:"Farm Frites", name:"فارم فريتس بطاطس بوم فريت - 1 كجم", category:"مجمدات", size:"1 كجم", referencePrice:66.5, image:"" },
  { masterId:"farmfrites-fries-25kg", brand:"Farm Frites", name:"فارم فريتس بطاطس بوم فريت - 2.5 كجم", category:"مجمدات", size:"2.5 كجم", referencePrice:167.99, image:"" },
  { masterId:"americana-molokhia-400", brand:"Americana", name:"أمريكانا ملوخية مجمدة - 400 جم", category:"مجمدات", size:"400 جم", referencePrice:17.99, image:"" },
  { masterId:"atyab-strips-1kg", brand:"Atyab", name:"أطياب تشيكن ستربس - 1 كجم", category:"مجمدات", size:"1 كجم", referencePrice:339.99, image:"" },
  { masterId:"atyab-burger-1kg", brand:"Atyab", name:"أطياب برجر لحم - 1 كجم", category:"مجمدات", size:"1 كجم", referencePrice:290.99, image:"" }
]);


export const MASTER_ID_ALIASES = Object.freeze({
  "water-15l":"water-aquafina-15l",
  "cola-can":"pepsi-300ml",
  "cola-1l":"cocacola-950ml",
  "juice-1l":"juhayna-apple-1l",
  "milk-1l":"beyti-milk-900ml",
  "yogurt":"juhayna-greek-yogurt-180g",
  "white-cheese":"domty-feta-250g",
  "eggs-12":"royal-eggs-30",
  "sugar-1kg":"aldoha-sugar-1kg",
  "rice-1kg":"aldoha-rice-1kg",
  "pasta-400g":"regina-spaghetti-400g",
  "oil-1l":"crystal-oil-1l",
  "tea":"lipton-tea-100g",
  "coffee":"nescafe-classic-190g",
  "chips":"chipsy-cheese-140g",
  "dish-soap":"fairy-lemon-620g",
  "laundry-powder":"persil-lavender-1kg",
  "soap":"lux-soap-4x115g",
  "toothpaste":"signal-anticavity-120ml"
});

export function canonicalMasterId(masterId) {
  const id=String(masterId||"").trim();
  return MASTER_ID_ALIASES[id] || id;
}

export const LEGACY_MASTER_NAME_MAP = Object.freeze({
  "water-15l":"مياه معدنية 1.5 لتر",
  "water-600ml":"مياه معدنية 600 مل",
  "cola-1l":"مشروب كولا حوالي 1 لتر",
  "cola-can":"مشروب غازي عبوة صغيرة",
  "juice-1l":"عصير كلاسيك 1 لتر",
  "milk-1l":"لبن كامل الدسم 1 لتر",
  "yogurt":"زبادي طبيعي",
  "white-cheese":"جبنة بيضاء",
  "eggs-12":"بيض أبيض",
  "sugar-1kg":"سكر أبيض 1 كجم",
  "rice-1kg":"أرز أبيض مصري 1 كجم",
  "pasta-400g":"مكرونة 400 جم",
  "oil-1l":"زيت عباد الشمس 1 لتر",
  "tea":"شاي أسود",
  "coffee":"قهوة سريعة الذوبان",
  "chips":"سناكس / مقرمشات",
  "biscuits":"بسكويت شاي",
  "chocolate":"شوكولاتة / ويفر",
  "tissues":"مناديل ورقية",
  "dish-soap":"سائل غسيل أطباق",
  "laundry-powder":"مسحوق غسيل",
  "soap":"صابون استحمام",
  "shampoo":"شامبو",
  "toothpaste":"معجون أسنان"
});

export const SUPERMARKET_CATEGORIES = Object.freeze(
  [...new Set(SUPERMARKET_MASTER_CATALOG.map(item => item.category))]
);

export function findMasterProduct(masterId) {
  const canonical=canonicalMasterId(masterId);
  return SUPERMARKET_MASTER_CATALOG.find(item => item.masterId === canonical) || null;
}
